---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon
  labels:
    author: intelliqit
spec:
  selector:
    matchLabels:
      author: intelliqit
  template:
    metadata:
      name: nginx-pod
      labels:
        author: intelliqit
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
...
