---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    author: intelliqit
    type: webserver
spec:
 replicas: 3
 template:
   metadata:
     name: httpd-pod
     labels:
       type: webserver
       author: intelliqit
   spec:
     containers:
       - name: myhttpd
         image: httpd
         ports:
           - containerPort: 80
             hostPort: 8080




