---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
      resources:
        requests:
          cpu: "100m"
          memory: "1Mi"
        limits:
          cpu: "150m"
          memory: "2Mi"
...
