---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: slave1
      operator: Equal
      value: intelliqit1
      effect: NoSchedule
