apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mywordpress
  name: mywordpress
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mywordpress
    spec:
      containers:
      - image: wordpress
        name: mywordpress
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
